In [11]:
class BinaryTree:
    def __init__(self, value):
        self.value = value
        self.LTree = None
        self.RTree = None
        
    def _add(self, tree, value):
        if tree:
            tree.add(value)
        else:
            tree = BinaryTree(value)
        return tree
            
    def add(self, value): 
        if value > self.value:
            self.RTree = self._add(self.RTree, value)
        elif value < self.value:
            self.LTree = self._add(self.LTree, value)
            
    def out(self):
        if self.LTree:
            self.LTree.out()
        if self.RTree:
            self.RTree.out()
        print(self.value)

In [1]:
import random
import numpy as np

In [16]:
%%time
tree = BinaryTree(782)
for i in range(100000):
    tree.add(random.randint(-10000000,10000000))
#tree.out()

Wall time: 1.4 s


In [ ]:
class DecisionTree : BinaryTree
    def __init__(self):
        super.__init__(self)
        self.X = None
        self.y = None
    
    def IGini(self, feature):
        Gini = lambda target: sum([y == 1 for y in target])
        for index, _ in enumerate(feature):
            left, right = feature[:index], feature[index:]
            max = (len(left) / len(feature)) * Gini(left)
            + (len(right) / len(feature)) * Gini(right)
        
    def fit(self, X, y):
        for feature in X: ## in sorted X
            IGain(feature)

In [58]:
X = np.ndarray([10,8])

In [78]:
X[0][:]

array([ 2.54034661e+151,  2.57408076e+151,  6.96225610e-305,
       -3.38460910e+125,  1.03156610e+113,  3.03470791e-298,
        3.69825575e+183,  4.81227688e+233])

In [60]:
X

array([[ 2.54034661e+151,  2.57408076e+151,  6.96225610e-305,
        -3.38460910e+125,  1.03156610e+113,  3.03470791e-298,
         3.69825575e+183,  4.81227688e+233],
       [ 1.33360385e+241,  1.06171937e-309,  1.32151025e-186,
         1.19770240e-315,  2.31581859e-289,  2.62011568e+063,
         9.04067648e+223,  2.55172779e+151],
       [ 2.57408076e+151,  1.75393304e-321,  1.08646185e-311,
         1.45314272e-308,  5.83336934e-302,  8.36749582e-085,
         2.64685961e+180,  3.98210433e+209],
       [ 1.57262256e-118,  3.06250777e+257,  5.98150353e-154,
        -1.24557420e+012,  2.83556550e-302,  1.71359658e-309,
        -1.23695058e+012,  4.14734130e-312],
       [ 3.53208746e-308,  3.13151306e-294,  4.23820020e+175,
         6.96055573e+252,  1.29173211e+171,  5.06769522e-314,
         4.24399158e-314,  1.42173718e-312],
       [ 6.71585298e+091,  1.05629353e-309,  6.69373695e-312,
         5.25339938e-305,  1.33360385e+241,  2.53938761e+151,
         3.53609246e-308,  7.29

In [1]:
import urllib.request
import re
import pandas as pd
import numpy as np

In [32]:
with urllib.request.urlopen('https://eralash.ru/library/1974/1') as response:
   html = response.read()
html = html.decode()

In [34]:
html[400:700]

'/ foaf: http://xmlns.com/foaf/0.1/ rdfs: http://www.w3.org/2000/01/rdf-schema# sioc: http://rdfs.org/sioc/ns# sioct: http://rdfs.org/sioc/types# skos: http://www.w3.org/2004/02/skos/core# xsd: http://www.w3.org/2001/XMLSchema#"><!--<![endif]-->\n<head>\n<link rel="apple-touch-icon" sizes="180x180" hre'

In [45]:
re.findall('<div class="field-content"><strong>Описание:</strong>.+</div>',html)

['<div class="field-content"><strong>Описание:</strong> История о том, как мальчик испачкал нос в чернилах и как на это отреагировали его одноклассники (по стихотворению А. Барто).</div>  </div>  </div>',
 '<div class="field-content"><strong>Описание:</strong> Мальчик едет в лифте с соседом. И рассказывает ему историю про велосипед на «своем» языке (Как Фитиль облапошил Шнобеля). Затем мужчина спрашивает у мальчика, что он проходит по литературе. Узнав, что мальчик изучает Гоголя, его сосед процитировал одно из произведений на языке «молодежи».</div>  </div>  </div>',
 '<div class="field-content"><strong>Описание:</strong> Из окна школы валит дым. Дети выбегают на улицу. Случайный прохожий вызывает пожарных. Оказывается, никакого пожара не было – это в туалете курят ребята. Пожарный падает в обморок от густого дыма и один из заядлых курильщиков говорит:  «Слабак! Сразу видно – некурящий!»</div>  </div>  </div>']

In [46]:
re.findall('<span class="field-content"><h2>.+</h2></span>',html)

['<span class="field-content"><h2>Сюжет № 1  "Позорное пятно"</h2></span>',
 '<span class="field-content"><h2>Сюжет № 2  "Почему мы так говорим?"</h2></span>',
 '<span class="field-content"><h2>Сюжет № 3  "Дым, дым, дым"</h2></span>']

In [87]:
desc = []
for string in re.findall('<span class="field-content"><h2>.+</h2></span>',html):
    string = re.sub(
        r'<.*>Сюжет № \d+', "",
        string
    )
    string = re.sub(
        r'</.*>', "",
        string
    )
    desc.append(string[3:-1])

In [88]:
desc

['Позорное пятно', 'Почему мы так говорим?', 'Дым, дым, дым']

In [93]:
series = []
for string in re.findall('<div class="field-content"><strong>Описание:</strong>.+</div>',html):
    string = re.sub(
        r'<.*>Описание:</strong>', "",
        string
    )
    string = re.sub(
        r'</.*>', "",
        string
    )
    series.append(string[1:-1])

In [94]:
series

['История о том, как мальчик испачкал нос в чернилах и как на это отреагировали его одноклассники (по стихотворению А. Барто)',
 'Мальчик едет в лифте с соседом. И рассказывает ему историю про велосипед на «своем» языке (Как Фитиль облапошил Шнобеля). Затем мужчина спрашивает у мальчика, что он проходит по литературе. Узнав, что мальчик изучает Гоголя, его сосед процитировал одно из произведений на языке «молодежи»',
 'Из окна школы валит дым. Дети выбегают на улицу. Случайный прохожий вызывает пожарных. Оказывается, никакого пожара не было – это в туалете курят ребята. Пожарный падает в обморок от густого дыма и один из заядлых курильщиков говорит:  «Слабак! Сразу видно – некурящий!']

In [95]:
## https://eralash.ru/library/anthology

In [111]:
def parse(url: str, year: int):
    with urllib.request.urlopen(url) as response:
        html = response.read()
    html = html.decode()
    desc = []
    for string in re.findall('<span class="field-content"><h2>.+</h2></span>',html):
        string = re.sub(
            r'<.*>Сюжет № \d+', "",
            string
        )
        string = re.sub(
            r'</.*>', "",
            string
        )
        desc.append(string)
    series = []
    for string in re.findall(r'''<div class="views-field views-field-field-video">.*<div class="field-content">.*<strong>.*</strong>.*</div>''',html):
        print(string)
        string = re.sub(
            r'<.*>.*:</strong>', "",
            string
        )
        string = re.sub(
            r'</.*>', "",
            string
        )
        series.append(string)
    print(np.array([desc, series, [str(year)]*len(desc)]))
    #return pd.DataFrame(np.array([desc, series, [str(year)]*len(desc)]).T,columns = ['Название','Описание','Год'])

In [112]:
parse(f'http://eralash.ru/library/{page}/{index}', page)

<div class="field-content"><strong>Описание:</strong> Совсем коротенькая история из бесконечной игры «Почемучки»</div>  </div>  </div>
<div class="field-content"><strong>Описание:</strong> Вполне правдоподобная беседа у памятника писателю-классику </div>  </div>  </div>
<div class="field-content"><strong>Описание:</strong> Приключение, из которого выясняется, что при случае помочь человеку не каждый может</div>  </div>  </div>
<div class="field-content"><strong>Описание:</strong> Забавная история о том, как хорошо быть находчивым, когда пропускаешь школу</div>  </div>  </div>
<div class="field-content"><strong>Описание:</strong> СЕРЕНАДА</div>  </div>  </div>
[list(['  "Почему?"', '  "Ну и дела!"', '  "Самый умный"', '  "Помогите!"', '  "Кто там?"', '  "Серенада"'])
 list([' Совсем коротенькая история из бесконечной игры «Почемучки»', ' Вполне правдоподобная беседа у памятника писателю-классику ', ' Приключение, из которого выясняется, что при случае помочь человеку не каждый может', '

c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\ipykernel_launcher.py:28: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray


In [12]:
page = 1981
df = pd.DataFrame()
for index in range(29,342):
    while(re.findall('<span class="field-content"><h2>.+</h2></span>',urllib.request.urlopen(f'http://eralash.ru/library/{page}/{index}').read().decode()) == []):
        page += 1
    print(page,index)
    df = pd.concat([df, parse(f'http://eralash.ru/library/{page}/{index}', page)])

1981 29


c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\ipykernel_launcher.py:27: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray


ValueError: Shape of passed values is (3, 1), indices imply (3, 3)

In [15]:
df

Empty DataFrame
Columns: []
Index: []

In [16]:
df.to_csv('er.csv')

In [1]:
import random

In [3]:
data = []
target, line = [], []
for i in range(7000):
    a = random.randint(0,100)
    b = random.randint(0,100)
    c = random.randint(0,100)
    d = random.randint(0,100)
    e = random.randint(0,100)
    line = [1,a,b,c,e,d]
    data.append(line)
    target.append(-375 + 73*a + 35*c + e + 57*d)

In [4]:
class LinearRegression:
    def __init__(self, alpha, eps):
        self.eps = eps
        self.alpha = alpha
        self.weights = []
        
    def predict(self, X):
        sum = 0
        for i in range(len(X)):
            sum += X[i] * self.weights[i]
        return sum
    
    def fit(self, data, target):
        size = len(target)
        step = 0
        self.weights = [0] * len(data[0])
        sample = random.randint(0,size-1)
        X = data[sample]
        error = target[sample] - self.predict(X)
        while error * error > self.eps:
            sample = random.randint(0,size-1)
            X = data[sample]
            error = target[sample] - self.predict(X)
            for i in range(len(X)):
                self.weights[i] -= -2 * self.alpha * error * X[i]
        print("[ERROR] "+str(error))
        print("[WEIGHTS] ")
        for weight in self.weights:
            print(weight)

In [23]:
reg = LinearRegression(1e-5, 5e-12)

In [24]:
%%time
reg.fit(data, target)

[ERROR] -2.2202748368727043e-06
[WEIGHTS] 
-364.81911374175104
72.97406940947732
-0.044201573222463236
34.97045855867238
0.9657701349513069
56.97134514519801
Wall time: 12.8 s


In [62]:
from sklearn.linear_model import LinearRegression as LR

In [63]:
reg2 = LR()

In [64]:
%%time
reg2.fit(data,target)

Wall time: 358 ms


LinearRegression()

In [65]:
reg2.coef_

array([ 0.00000000e+00,  7.35000000e+02, -2.84217094e-14,  3.57000000e+02,
        1.00000000e+00,  5.73000000e+02])

In [67]:
reg.predict((1, 100,100,100,100,100))

166224.7574923259

In [69]:
reg2.predict([[1, 100,100,100,100,100]])

array([166225.])